//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta geçerli değil!.
        /// </summary>
        internal static string Account_EmailIsNotValid {
            get {
                return ResourceManager.GetString("Account_EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        internal static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Account_Login {
            get {
                return ResourceManager.GetString("Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminize devam etmek için üye girişi yapmalısınız!.
        /// </summary>
        internal static string Account_LoginMessage {
            get {
                return ResourceManager.GetString("Account_LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Girişi.
        /// </summary>
        internal static string Account_LoginTitle {
            get {
                return ResourceManager.GetString("Account_LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string Account_Logout {
            get {
                return ResourceManager.GetString("Account_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabım.
        /// </summary>
        internal static string Account_MyAccount {
            get {
                return ResourceManager.GetString("Account_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilerim.
        /// </summary>
        internal static string Account_MyInfo {
            get {
                return ResourceManager.GetString("Account_MyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        internal static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        internal static string Account_RememberMe {
            get {
                return ResourceManager.GetString("Account_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malesef semt seçiminizi kaydedemedik!.
        /// </summary>
        internal static string Address_RegionCannotBeRefreshed {
            get {
                return ResourceManager.GetString("Address_RegionCannotBeRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Al.
        /// </summary>
        internal static string Basket_CompletePurchasing {
            get {
                return ResourceManager.GetString("Basket_CompletePurchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişe devam.
        /// </summary>
        internal static string Basket_ContinueShopping {
            get {
                return ResourceManager.GetString("Basket_ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ürününü sepetinizden çıkarmak istediğinizden emin misiniz?.
        /// </summary>
        internal static string Basket_DeleteConfirmSubtext {
            get {
                return ResourceManager.GetString("Basket_DeleteConfirmSubtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete Git.
        /// </summary>
        internal static string Basket_GoToBasket {
            get {
                return ResourceManager.GetString("Basket_GoToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün sepetinize başarıyla eklendi. Şimdi ne yapmak istersiniz?.
        /// </summary>
        internal static string Basket_ItemAddedToBasket {
            get {
                return ResourceManager.GetString("Basket_ItemAddedToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorilerim.
        /// </summary>
        internal static string Basket_MyFavorites {
            get {
                return ResourceManager.GetString("Basket_MyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetinizde henüz ürün yok...
        /// </summary>
        internal static string Basket_NoItemAvailable {
            get {
                return ResourceManager.GetString("Basket_NoItemAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepet Özeti.
        /// </summary>
        internal static string Basket_SummaryTitle {
            get {
                return ResourceManager.GetString("Basket_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kdv Dahil Toplam :.
        /// </summary>
        internal static string Basket_TaxAddedTotal {
            get {
                return ResourceManager.GetString("Basket_TaxAddedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetim.
        /// </summary>
        internal static string Basket_Title {
            get {
                return ResourceManager.GetString("Basket_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyalar.
        /// </summary>
        internal static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapalı.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta Adresi.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sss.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkiye’nin ilk sanal market uygulaması olan WebMarket.com Türkiye’nin marketçilik alanında en büyük e-ticaret sitesi
        ///                            olma vizyonuyla, 2015 yılında siz değerli müşterilerine hizmet hayatına başlamıştır..
        /// </summary>
        internal static string Footer_AboutText {
            get {
                return ResourceManager.GetString("Footer_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıkça Sorulan Sorular.
        /// </summary>
        internal static string Footer_FAQ {
            get {
                return ResourceManager.GetString("Footer_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yardım.
        /// </summary>
        internal static string Footer_Help {
            get {
                return ResourceManager.GetString("Footer_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlginizi Çekebilir.
        /// </summary>
        internal static string Footer_Interests {
            get {
                return ResourceManager.GetString("Footer_Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya.
        /// </summary>
        internal static string Footer_SocialMedia {
            get {
                return ResourceManager.GetString("Footer_SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirimdekiler.
        /// </summary>
        internal static string Home_DiscountedItems {
            get {
                return ResourceManager.GetString("Home_DiscountedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürünler.
        /// </summary>
        internal static string Home_NewItems {
            get {
                return ResourceManager.GetString("Home_NewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fırsat Ürünleri.
        /// </summary>
        internal static string Home_OpportunityItems {
            get {
                return ResourceManager.GetString("Home_OpportunityItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhangi bir sonuç bulunamadı!.
        /// </summary>
        internal static string NoSearchResultFound {
            get {
                return ResourceManager.GetString("NoSearchResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teşekkürler! Siparişiniz Bize Ulaştı..
        /// </summary>
        internal static string Order_ApprovedMessage {
            get {
                return ResourceManager.GetString("Order_ApprovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Zamanı.
        /// </summary>
        internal static string Order_Date {
            get {
                return ResourceManager.GetString("Order_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim.
        /// </summary>
        internal static string Order_Discount {
            get {
                return ResourceManager.GetString("Order_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Tutarı.
        /// </summary>
        internal static string Order_GrossTotal {
            get {
                return ResourceManager.GetString("Order_GrossTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş No.
        /// </summary>
        internal static string Order_No {
            get {
                return ResourceManager.GetString("Order_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henüz bir siparişiniz yok...
        /// </summary>
        internal static string Order_NoOrderMessage {
            get {
                return ResourceManager.GetString("Order_NoOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Durumu.
        /// </summary>
        internal static string Order_Status {
            get {
                return ResourceManager.GetString("Order_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişlerim.
        /// </summary>
        internal static string Order_Title {
            get {
                return ResourceManager.GetString("Order_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bekleyiniz....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aramanıza uygun semt bulunamadı!.
        /// </summary>
        internal static string Region_NoRegionFound {
            get {
                return ResourceManager.GetString("Region_NoRegionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt ara...
        /// </summary>
        internal static string Region_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Region_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz değil marketler ayağınıza gelsin. Türkiye&apos;nin en büyük online marketi &lt;b&gt;Webmarket.com&lt;/b&gt; bir tık ötede.&lt;br&gt;
        ///        Size daha özel hizmet verebilmemiz için &quot;Semtinizi Seçin&quot;..
        /// </summary>
        internal static string Region_SubTitle {
            get {
                return ResourceManager.GetString("Region_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün, kategori ara.
        /// </summary>
        internal static string SearchItem {
            get {
                return ResourceManager.GetString("SearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt Seç.
        /// </summary>
        internal static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişe Başla.
        /// </summary>
        internal static string StartPurchase {
            get {
                return ResourceManager.GetString("StartPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketler.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu markette yer  alan ürünler.
        /// </summary>
        internal static string Store_ItemsTitle {
            get {
                return ResourceManager.GetString("Store_ItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketler.
        /// </summary>
        internal static string Store_ListTitle {
            get {
                return ResourceManager.GetString("Store_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Sipariş Tutarı :.
        /// </summary>
        internal static string Store_MinOrderAmount {
            get {
                return ResourceManager.GetString("Store_MinOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu market servis yaptığı bir bölge yok!.
        /// </summary>
        internal static string Store_NoServiceRegionFound {
            get {
                return ResourceManager.GetString("Store_NoServiceRegionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semtinize hizmet veren herhangi bir market bulunamadı!.
        /// </summary>
        internal static string Store_NoStoreMessage {
            get {
                return ResourceManager.GetString("Store_NoStoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semtinize servis yapan marketleri görüntülemek için öncelikle semt seçimi yapmalısınız!.
        /// </summary>
        internal static string Store_SelectRegionMessage {
            get {
                return ResourceManager.GetString("Store_SelectRegionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis Bölgeleri.
        /// </summary>
        internal static string Store_ServiceRegions {
            get {
                return ResourceManager.GetString("Store_ServiceRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semtinize servis yapan marketleri inceleyin, ürün fiyatlarını karşılaştırın. Hızlı, ucuz ve güvenli alışverişin tadını çıkarın..
        /// </summary>
        internal static string Store_SubTitle {
            get {
                return ResourceManager.GetString("Store_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Saatleri.
        /// </summary>
        internal static string Store_WorkTimeInfo {
            get {
                return ResourceManager.GetString("Store_WorkTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
