//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aware {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aware.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres silinirken bir hata oluştu!.
        /// </summary>
        public static string Address_AddressCannotBeDeleted {
            get {
                return ResourceManager.GetString("Address_AddressCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres düzenlenirken bir hata oluştu!.
        /// </summary>
        public static string Address_AddressCannotBeEdited {
            get {
                return ResourceManager.GetString("Address_AddressCannotBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En fazla 5 tane adres ekleyebilirsiniz!.
        /// </summary>
        public static string Address_MaxAddressCountExceeded {
            get {
                return ResourceManager.GetString("Address_MaxAddressCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklemeye çalıştığınız yetki zaten tanımlanmış. Lütfeden listeden  seçim yaparak düzenleyin..
        /// </summary>
        public static string Authority_ValueExists {
            get {
                return ResourceManager.GetString("Authority_ValueExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz favori ürün/ler sepetinize eklenemedi. Lütfen daha sonra tekrar deneyiniz..
        /// </summary>
        public static string Basket_AddFavoritesToBasketFailed {
            get {
                return ResourceManager.GetString("Basket_AddFavoritesToBasketFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz favori ürün/lerden bir kısmı sepetinize eklenemedi..
        /// </summary>
        public static string Basket_AddFavoritesToBasketPartiallyFailed {
            get {
                return ResourceManager.GetString("Basket_AddFavoritesToBasketPartiallyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz favori ürün/ler başarıyla sepetinize eklendi..
        /// </summary>
        public static string Basket_AddFavoritesToBasketSuccessfull {
            get {
                return ResourceManager.GetString("Basket_AddFavoritesToBasketSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün sepetinize eklenemedi!.
        /// </summary>
        public static string Basket_AddToBasketFailed {
            get {
                return ResourceManager.GetString("Basket_AddToBasketFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün başarıyla favorilerinize eklendi..
        /// </summary>
        public static string Basket_AddToFavoriteSuccessfull {
            get {
                return ResourceManager.GetString("Basket_AddToFavoriteSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün sepetinizden şuan çıkartılamıyor. Lütfen daha sonra tekrar deneyin!.
        /// </summary>
        public static string Basket_ItemCannotBeDeleted {
            get {
                return ResourceManager.GetString("Basket_ItemCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün sepetinizden başarıyla çıkartıldı..
        /// </summary>
        public static string Basket_ItemDeletedSuccessfully {
            get {
                return ResourceManager.GetString("Basket_ItemDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün bulunamadı!.
        /// </summary>
        public static string Basket_ItemNotFound {
            get {
                return ResourceManager.GetString("Basket_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün stoğu yeterli olmadığından, ürün sepetinize eklenemedi..
        /// </summary>
        public static string Basket_NotEnoughStock {
            get {
                return ResourceManager.GetString("Basket_NotEnoughStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetinize bu üründen en fazla {0} {1} ekleyebilirsiniz!.
        /// </summary>
        public static string Basket_QuantityLimitExceeded {
            get {
                return ResourceManager.GetString("Basket_QuantityLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorilerden kadırma işlemi başarısız oldu!.
        /// </summary>
        public static string Basket_RemoveFromFavoriteFailed {
            get {
                return ResourceManager.GetString("Basket_RemoveFromFavoriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün/ler başarıyla favorilerinizden kaldırıldı!.
        /// </summary>
        public static string Basket_RemoveFromFavoriteSuccessfull {
            get {
                return ResourceManager.GetString("Basket_RemoveFromFavoriteSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetinizde yalnızca bir markete ait ürünler yer alabilir. Bu ürünü sepetinize eklemek için öncelikle sepetinizdeki ürünleri çıkartın!.
        /// </summary>
        public static string Basket_SingleStoreAllowed {
            get {
                return ResourceManager.GetString("Basket_SingleStoreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün için varyant seçimi yapmalısınız!.
        /// </summary>
        public static string Basket_VariantSelectionRequired {
            get {
                return ResourceManager.GetString("Basket_VariantSelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupon kodunuz başarıyla sepetinize uygulandı..
        /// </summary>
        public static string Campaign_CouponCodeAppliedSuccessfully {
            get {
                return ResourceManager.GetString("Campaign_CouponCodeAppliedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kupon kodu zaten kullanılmış!.
        /// </summary>
        public static string Campaign_CouponCodeIsAlreadyUsed {
            get {
                return ResourceManager.GetString("Campaign_CouponCodeIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirttiğiniz kupon kodunun süresi dolmuş!.
        /// </summary>
        public static string Campaign_CouponCodeIsExpired {
            get {
                return ResourceManager.GetString("Campaign_CouponCodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz bir kupon kodu belirttiniz!.
        /// </summary>
        public static string Campaign_CouponCodeIsNotValid {
            get {
                return ResourceManager.GetString("Campaign_CouponCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart numarası geçerli değil!.
        /// </summary>
        public static string Card_InvalidCardNumber {
            get {
                return ResourceManager.GetString("Card_InvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik anahatarı (CVC) geçerli değil!.
        /// </summary>
        public static string Card_InvalidCVC {
            get {
                return ResourceManager.GetString("Card_InvalidCVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son kullanma tarihi geçerli değil!.
        /// </summary>
        public static string Card_InvalidExpireDate {
            get {
                return ResourceManager.GetString("Card_InvalidExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum durumu başarıyla güncellendi..
        /// </summary>
        public static string Comment_ChangeStatus_Successfull {
            get {
                return ResourceManager.GetString("Comment_ChangeStatus_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum içeriğinde argo/küfür içeren sözcükler tespit edildi. Lütfen kontrol ederek tekrar deneyiniz!.
        /// </summary>
        public static string Comment_ContentContainsAbusiveWord {
            get {
                return ResourceManager.GetString("Comment_ContentContainsAbusiveWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum içeriği çok kısa. Beş kelimeden az yazılmış yorumlar onaylanmamaktadır!.
        /// </summary>
        public static string Comment_ContentMinLengthError {
            get {
                return ResourceManager.GetString("Comment_ContentMinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum başlığında argo/küfür içeren sözcükler tespit edildi. Lütfen kontrol ederek tekrar deneyiniz!.
        /// </summary>
        public static string Comment_TitleContainsAbusiveWord {
            get {
                return ResourceManager.GetString("Comment_TitleContainsAbusiveWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün favorilerinize eklenemedi. Lütfen daha sonra tekrar deneyiniz!.
        /// </summary>
        public static string Favorite_AddToFavoritesFailed {
            get {
                return ResourceManager.GetString("Favorite_AddToFavoritesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtilen dosya sistemde mevcut değil ya da  işlem başarısız!.
        /// </summary>
        public static string File_NotAvailable {
            get {
                return ResourceManager.GetString("File_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarısız. Lütfen daha sonra tekrar deneyiniz..
        /// </summary>
        public static string General_Error {
            get {
                return ResourceManager.GetString("General_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili istek işlenirken bir hata oluştu!.
        /// </summary>
        public static string General_ExceptionThrowed {
            get {
                return ResourceManager.GetString("General_ExceptionThrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarıyla tamamlandı..
        /// </summary>
        public static string General_Success {
            get {
                return ResourceManager.GetString("General_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme işlemine devam edilemiyor. Lütfen daha sonra tekrar deneyin!.
        /// </summary>
        public static string Order_CannotPaidWithCreditCard {
            get {
                return ResourceManager.GetString("Order_CannotPaidWithCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GarantiPay üzerinden ödeme işlemine devam edilemiyor. Lütfen daha sonra tekrar deneyin!.
        /// </summary>
        public static string Order_CannotPaidWithGarantiPay {
            get {
                return ResourceManager.GetString("Order_CannotPaidWithGarantiPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş ödemesi alındı fakat sistemimize işlenemedi. Lütfen müşteri temsilcimiz ile iletişime geçin!.
        /// </summary>
        public static string Order_CompletePaymentFailed {
            get {
                return ResourceManager.GetString("Order_CompletePaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nolu siparişiniz sistemde bulunamadı! Lütfen müşteri temsilcimiz ile iletişime geçin!.
        /// </summary>
        public static string Order_CompletePaymentFailedSinceOrderNotFound {
            get {
                return ResourceManager.GetString("Order_CompletePaymentFailedSinceOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetinizde henüz ürün yok. Sipariş vermek için sepetinize ürün eklemelisiniz!.
        /// </summary>
        public static string Order_NoBasketNoItem {
            get {
                return ResourceManager.GetString("Order_NoBasketNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişiniz onaylanırken bir hata oluştu!.
        /// </summary>
        public static string Order_OrderCannotBeApproved {
            get {
                return ResourceManager.GetString("Order_OrderCannotBeApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece onay bekleyen veya ödemesi yapılmamış siparişlerinizi iptal edebilirsiniz!.
        /// </summary>
        public static string Order_OrderCannotBeCancelled {
            get {
                return ResourceManager.GetString("Order_OrderCannotBeCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişiniz düzenlenirken bir hata oluştu!.
        /// </summary>
        public static string Order_OrderCannotBeEdited {
            get {
                return ResourceManager.GetString("Order_OrderCannotBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş ödeme bilgileri kaydedilemedi. Lütfen daha sonra tekrar deneyin!.
        /// </summary>
        public static string Order_PaymentInfoCannotBeSaved {
            get {
                return ResourceManager.GetString("Order_PaymentInfoCannotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam etmek için havale yapacağınız bankayı seçmelisiniz!.
        /// </summary>
        public static string Order_RemittanceBankNotSelected {
            get {
                return ResourceManager.GetString("Order_RemittanceBankNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepet tutarınız, minimum sipariş tutarı {0}&apos;nin üstünde olmalıdır!.
        /// </summary>
        public static string Order_StoreMinAmountNotPassed {
            get {
                return ResourceManager.GetString("Order_StoreMinAmountNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankadan dönen cevap okunamadı!.
        /// </summary>
        public static string Payment_BankResponseNotReadable {
            get {
                return ResourceManager.GetString("Payment_BankResponseNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölgenin alt bölgeleri olduğu için bu bölge silinemez!.
        /// </summary>
        public static string RegionDelete_RegionHasSubegions {
            get {
                return ResourceManager.GetString("RegionDelete_RegionHasSubegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz ürün bu markete zaten eklenmiş!.
        /// </summary>
        public static string Store_AlreadyHasItem {
            get {
                return ResourceManager.GetString("Store_AlreadyHasItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün aktarımı yapılamıyor. Geçersiz bir dosya ile istek yapıldı!.
        /// </summary>
        public static string StoreItem_ImportInvalidFile {
            get {
                return ResourceManager.GetString("StoreItem_ImportInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün aktarım işlemi başarısız oldu!.
        /// </summary>
        public static string StoreItem_ImportOperationFailed {
            get {
                return ResourceManager.GetString("StoreItem_ImportOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünlerin aktarımı başarıyla tamamlandı..
        /// </summary>
        public static string StoreItem_ImportOperationSuccessfull {
            get {
                return ResourceManager.GetString("StoreItem_ImportOperationSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeliğiniz başarıyla aktive edildi..
        /// </summary>
        public static string User_ActivationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("User_ActivationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivasyon kodunun süresi bitmiş. Lütfen yenisini talep ediniz!.
        /// </summary>
        public static string User_ActivationLinkExpired {
            get {
                return ResourceManager.GetString("User_ActivationLinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi güncelleyebilmeniz için &apos;{0}&apos; e-posta adresine bir aktivasyon maili gönderdik..
        /// </summary>
        public static string User_ActivationLinkSend1 {
            get {
                return ResourceManager.GetString("User_ActivationLinkSend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeliğinizi aktifleştirebilmeniz için &apos;{0}&apos; e-posta adresine bir aktivasyon maili gönderdik..
        /// </summary>
        public static string User_ActivationLinkSend2 {
            get {
                return ResourceManager.GetString("User_ActivationLinkSend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeliğiniz henüz aktive edilmemiş..
        /// </summary>
        public static string User_ActivationRequired {
            get {
                return ResourceManager.GetString("User_ActivationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik aktivasyonunuz daha önce zaten yapılmış. Bilgilerinizle üye girişi yapabilirsiniz..
        /// </summary>
        public static string User_AlreadyActivated {
            get {
                return ResourceManager.GetString("User_AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız başarıyla yöneticilerimize iletildi. Teşekkürler...
        /// </summary>
        public static string User_ContactUsMailSended {
            get {
                return ResourceManager.GetString("User_ContactUsMailSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifreniz mevcut şifreniz ile aynı olamaz!.
        /// </summary>
        public static string User_CurrentPasswordAndNewPasswordAreSame {
            get {
                return ResourceManager.GetString("User_CurrentPasswordAndNewPasswordAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta başka kullanıcıya ait!.
        /// </summary>
        public static string User_EmailExist {
            get {
                return ResourceManager.GetString("User_EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta geçerli değil!.
        /// </summary>
        public static string User_EmailIsNotValid {
            get {
                return ResourceManager.GetString("User_EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu e-postaya sahip bir kullanıcı bulunamadı!.
        /// </summary>
        public static string User_EmailNotExist {
            get {
                return ResourceManager.GetString("User_EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirttiğiniz aktivasyon kodu geçerli değildir..
        /// </summary>
        public static string User_InvalidActivationCode {
            get {
                return ResourceManager.GetString("User_InvalidActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut şifrenizi hatalı belirttiniz!.
        /// </summary>
        public static string User_InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("User_InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileriniz eksik!.
        /// </summary>
        public static string User_MissignInfo {
            get {
                return ResourceManager.GetString("User_MissignInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz değiştirilemedi. Lütfen bilgilerinizi kontrol edip tekrar deneyin!.
        /// </summary>
        public static string User_PasswordRefreshFailed {
            get {
                return ResourceManager.GetString("User_PasswordRefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı başarıyla oluşturuldu..
        /// </summary>
        public static string User_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("User_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı başarıyla silindi..
        /// </summary>
        public static string User_SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("User_SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bilgileri başarıyla kaydedildi..
        /// </summary>
        public static string User_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("User_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata! Ticket geçerli değil. Süresi dolmuş olabilir yada hatalı ticket belirtildi..
        /// </summary>
        public static string User_TicketIsNotValid {
            get {
                return ResourceManager.GetString("User_TicketIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403.
        /// </summary>
        public static string User_UnAuthorized {
            get {
                return ResourceManager.GetString("User_UnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta ya da şifreniz hatalı! Eğer şifrenizi hatırlamıyorsanız &apos;Şifremi Unuttum&apos; ekranında, şifre hatırlatma e-postası talebinde bulunabilirsiniz..
        /// </summary>
        public static string User_WrongInformation {
            get {
                return ResourceManager.GetString("User_WrongInformation", resourceCulture);
            }
        }
    }
}
